# MiaoplancommanNK 配置文件
# 最后修正 2020.1.1
# 配置文件已经全中文化 这下你们应该会用吧！
# 时间算法：1=1分钟
# 如果还要加添多条，记得再后面加上条数！如果格式错误本条循环命令将不执行！
# 打开网站http://bbs.i8mc.xyz 随时查看插件更新！
  您要执行的命令1: say 欢迎使用MiaoplancommanNK
  循环时间1: 1
  您要执行的命令2: say 这是第2条循环命令!
  循环时间2: 1
  您要执行的命令3: say 这是第3条循环命令!
  循环时间3: 1